services:

  tasks_service:
    build:
      context: ./tasks-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - tasks_service
      - user_service
    volumes:
      - ./webapp:/app
