services:

  tasks_service:
    build:
      context: ./tasks-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network

  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - app-network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - tasks_service
      - user_service
    volumes:
      - ./webapp:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
